### ISSUE TITLE
New client build

### ISSUE THREAD

**Issue by dlemmermann** [dlsc-software-consulting-gmbh/jfxcentral2#456]
Hi Mike, Release 7, v1.7.0 would be ready for your services :-)

**Comment by mikehearn** [comment]
This release is encountering a couple of difficulties and may take longer. Although there's an update that's been pushed,

1. I forgot to enable delta updates (it's opt in), oops. That's easily fixable.
2. For some reason, although it appeared to build and be releasable yesterday today I can't build the packages because:

```
Http: HTTP server returned 403 for https://download2.gluonhq.com/openjfx/21-ea+24/openjfx-21-ea+24_osx-x64_bin-jmods.zip
```

Indeed I don't see any JavaFX 21 releases supplied by Gluon. And checking the jdk.java.net site, I see only ea+30, with ea+24 having disappeared. So I think actually at the moment jmods for the version of JavaFX you're now using aren't available anywhere at all? The jmods are needed to build the downloads.

But this leads to the conclusion that maybe the release shouldn't have worked yesterday either, which is a bit puzzling.

**Comment by dlemmermann** [comment]
I changed the JavaFX version to "20". A few more fixes were also committed since yesterday, which is why I created Release 8, v1.8.0. Please use that one for the build.

**Comment by dlemmermann** [comment]
And another critical fix merged. Now please use v1.9.0

**Comment by mikehearn** [comment]
Done.

**Comment by mikehearn** [comment]
Delta updates are working now too, albeit the smallest possible update appears to be 13 megabytes for some reason. That's still a nearly 10x win, but these are tiny patches you're making. Why is the delta so large? Maybe the JARs aren't deterministic?

**Comment by dlemmermann** [comment]
Hmmm, not sure. But we did exchange the JGit implementation, which I assume is a rather big dependency chain.
