### ISSUE TITLE
Installation Failure Reports on Win11 - Need for Verification

### ISSUE THREAD

**Issue by leewyatt** [dlsc-software-consulting-gmbh/jfxcentral2#468]
I have shared the installation package in the Chinese fx community and received feedback indicating that users with Win11 are experiencing installation failures. As of now, As of now, there have been several reported cases of installation failure from users operating on Win11.

To better understand and address this issue, I plan to replicate the environment and verify the problem on a Win11 system. I am noting here for reference that the installation proceeded without issues on my Win10 system.

I would appreciate any insights or suggestions as we look into this matter. Thank you.
![image](https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/assets/75261429/c363fd2e-7e01-4503-a0c9-498c39f1354f)
![image](https://github.com/dlsc-software-consulting-gmbh/jfxcentral2/assets/75261429/b7c53ef3-0d2e-49d9-b22d-b2a4a63ffacc)

**Comment by mikehearn** [comment]
These are WININET_E_CANNOT_CONNECT and WININET_E_NAME_NOT_RESOLVED, i.e. network flakes, so this is very likely to be due to interference from the Chinese firewall. I don't think there's much we can do about that. Based on bitter experience, China's internet connectivity to the outside world has been broken to the point of being nearly worthless for many years. They get cut off if they try to do encrypted transfers that last longer than a few seconds, so downloads of a large file over SSL would do it.

I suspect we just have to accept this, unless someone else wants to take over hosting and establish a server in China.

**Comment by leewyatt** [comment]
@mikehearn Thank you for your patient explanation; I understand now. Perhaps we can close this issue for the time being.

**Comment by dlemmermann** [comment]
Out of scope. Outside our powers ....
